/***********************************************************************/
/*                                                                     */
/*      FILE         :  iodefine.h                                     */
/*      DESCRIPTION  :  Definition of I/O Registers                    */
/*      CPU SERIES   :  RL78 - G13                                     */
/*      CPU TYPE     :  R5F100SL                                       */
/*                                                                     */
/*      This file is generated by e2studio.                            */
/*                                                                     */
/***********************************************************************/

#ifndef IODEFINE_H
#define IODEFINE_H

/*
 IO Registers
 */
union un_p0 {
    unsigned char p0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p1 {
    unsigned char p1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p2 {
    unsigned char p2;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p3 {
    unsigned char p3;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p4 {
    unsigned char p4;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p5 {
    unsigned char p5;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p6 {
    unsigned char p6;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p7 {
    unsigned char p7;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p8 {
    unsigned char p8;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p9 {
    unsigned char p9;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p10 {
    unsigned char p10;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p11 {
    unsigned char p11;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p12 {
    unsigned char p12;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p13 {
    unsigned char p13;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p14 {
    unsigned char p14;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_p15 {
    unsigned char p15;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr00 {
    unsigned short sdr00;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_sio00 {
    unsigned char sio00;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_txd0 {
    unsigned char txd0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr01 {
    unsigned short sdr01;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_rxd0 {
    unsigned char rxd0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sio01 {
    unsigned char sio01;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr12 {
    unsigned short sdr12;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_sio30 {
    unsigned char sio30;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_txd3 {
    unsigned char txd3;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr13 {
    unsigned short sdr13;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_rxd3 {
    unsigned char rxd3;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sio31 {
    unsigned char sio31;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr00 {
    unsigned short tdr00;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr01 {
    unsigned short tdr01;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr01l {
    unsigned char tdr01l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr01h {
    unsigned char tdr01h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_adcr {
    unsigned short adcr;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_adcrh {
    unsigned char adcrh;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm0 {
    unsigned char pm0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm1 {
    unsigned char pm1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm2 {
    unsigned char pm2;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm3 {
    unsigned char pm3;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm4 {
    unsigned char pm4;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm5 {
    unsigned char pm5;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm6 {
    unsigned char pm6;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm7 {
    unsigned char pm7;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm8 {
    unsigned char pm8;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm9 {
    unsigned char pm9;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm10 {
    unsigned char pm10;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm11 {
    unsigned char pm11;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm12 {
    unsigned char pm12;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm14 {
    unsigned char pm14;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_pm15 {
    unsigned char pm15;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_adm0 {
    unsigned char adm0;
    struct {
        unsigned char adce :1;
        unsigned char :6;
        unsigned char adcs :1;
    } BIT;
};
union un_ads {
    unsigned char ads;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_adm1 {
    unsigned char adm1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_krm {
    unsigned char krm;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_egp0 {
    unsigned char egp0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_egn0 {
    unsigned char egn0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_egp1 {
    unsigned char egp1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_egn1 {
    unsigned char egn1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr02 {
    unsigned short sdr02;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_sio10 {
    unsigned char sio10;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_txd1 {
    unsigned char txd1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr03 {
    unsigned short sdr03;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_rxd1 {
    unsigned char rxd1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sio11 {
    unsigned char sio11;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr10 {
    unsigned short sdr10;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_sio20 {
    unsigned char sio20;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_txd2 {
    unsigned char txd2;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sdr11 {
    unsigned short sdr11;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_rxd2 {
    unsigned char rxd2;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_sio21 {
    unsigned char sio21;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_iica0 {
    unsigned char iica0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_iics0 {
    unsigned char iics0;
    struct {
        unsigned char spd0 :1;
        unsigned char std0 :1;
        unsigned char ackd0 :1;
        unsigned char trc0 :1;
        unsigned char coi0 :1;
        unsigned char exc0 :1;
        unsigned char ald0 :1;
        unsigned char msts0 :1;
    } BIT;
};
union un_iicf0 {
    unsigned char iicf0;
    struct {
        unsigned char iicrsv0 :1;
        unsigned char stcen0 :1;
        unsigned char :4;
        unsigned char iicbsy0 :1;
        unsigned char stcf0 :1;
    } BIT;
};
union un_iica1 {
    unsigned char iica1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_iics1 {
    unsigned char iics1;
    struct {
        unsigned char spd1 :1;
        unsigned char std1 :1;
        unsigned char ackd1 :1;
        unsigned char trc1 :1;
        unsigned char coi1 :1;
        unsigned char exc1 :1;
        unsigned char ald1 :1;
        unsigned char msts1 :1;
    } BIT;
};
union un_iicf1 {
    unsigned char iicf1;
    struct {
        unsigned char iicrsv1 :1;
        unsigned char stcen1 :1;
        unsigned char :4;
        unsigned char iicbsy1 :1;
        unsigned char stcf1 :1;
    } BIT;
};
union un_tdr02 {
    unsigned short tdr02;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr03 {
    unsigned short tdr03;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr03l {
    unsigned char tdr03l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr03h {
    unsigned char tdr03h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr04 {
    unsigned short tdr04;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr05 {
    unsigned short tdr05;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr06 {
    unsigned short tdr06;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr07 {
    unsigned short tdr07;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr10 {
    unsigned short tdr10;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr11 {
    unsigned short tdr11;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr11l {
    unsigned char tdr11l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr11h {
    unsigned char tdr11h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr12 {
    unsigned short tdr12;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr13 {
    unsigned short tdr13;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr13l {
    unsigned char tdr13l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr13h {
    unsigned char tdr13h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_tdr14 {
    unsigned short tdr14;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr15 {
    unsigned short tdr15;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr16 {
    unsigned short tdr16;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_tdr17 {
    unsigned short tdr17;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_flpmc {
    unsigned char flpmc;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_flars {
    unsigned char flars;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_flapl {
    unsigned short flapl;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_flaph {
    unsigned char flaph;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_fssq {
    unsigned char fssq;
    struct {
        unsigned char :6;
        unsigned char fsstp :1;
        unsigned char sqst :1;
    } BIT;
};
union un_flsedl {
    unsigned short flsedl;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_flsedh {
    unsigned char flsedh;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_flrst {
    unsigned char flrst;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_fsastl {
    unsigned char fsastl;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_fsasth {
    unsigned char fsasth;
    struct {
        unsigned char :6;
        unsigned char sqend :1;
        unsigned char esqend :1;
    } BIT;
};
union un_flwl {
    unsigned short flwl;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_flwh {
    unsigned short flwh;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_itmc {
    unsigned short itmc;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_sec {
    unsigned char sec;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_min {
    unsigned char min;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_hour {
    unsigned char hour;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_week {
    unsigned char week;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_day {
    unsigned char day;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_month {
    unsigned char month;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_year {
    unsigned char year;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_subcud {
    unsigned char subcud;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_alarmwm {
    unsigned char alarmwm;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_alarmwh {
    unsigned char alarmwh;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_alarmww {
    unsigned char alarmww;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_rtcc0 {
    unsigned char rtcc0;
    struct {
        unsigned char :5;
        unsigned char rcloe1 :1;
        unsigned char :1;
        unsigned char rtce :1;
    } BIT;
};
union un_rtcc1 {
    unsigned char rtcc1;
    struct {
        unsigned char rwait :1;
        unsigned char rwst :1;
        unsigned char :1;
        unsigned char rifg :1;
        unsigned char wafg :1;
        unsigned char :1;
        unsigned char walie :1;
        unsigned char wale :1;
    } BIT;
};
union un_cmc {
    unsigned char cmc;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_csc {
    unsigned char csc;
    struct {
        unsigned char hiostop :1;
        unsigned char :5;
        unsigned char xtstop :1;
        unsigned char mstop :1;
    } BIT;
};
union un_ostc {
    unsigned char ostc;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_osts {
    unsigned char osts;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_ckc {
    unsigned char ckc;
    struct {
        unsigned char :3;
        unsigned char sdiv :1;
        unsigned char mcm0 :1;
        unsigned char mcs :1;
        unsigned char css :1;
        unsigned char cls :1;
    } BIT;
};
union un_cks0 {
    unsigned char cks0;
    struct {
        unsigned char :7;
        unsigned char pcloe0 :1;
    } BIT;
};
union un_cks1 {
    unsigned char cks1;
    struct {
        unsigned char :7;
        unsigned char pcloe1 :1;
    } BIT;
};
union un_resf {
    unsigned char resf;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_lvim {
    unsigned char lvim;
    struct {
        unsigned char lvif :1;
        unsigned char lviomsk :1;
        unsigned char :5;
        unsigned char lvisen :1;
    } BIT;
};
union un_lvis {
    unsigned char lvis;
    struct {
        unsigned char lvilv :1;
        unsigned char :6;
        unsigned char lvimd :1;
    } BIT;
};
union un_wdte {
    unsigned char wdte;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_crcin {
    unsigned char crcin;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_rxb {
    unsigned char rxb;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_txs {
    unsigned char txs;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_monsta0 {
    unsigned char monsta0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_asim {
    unsigned char asim;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dsa0 {
    unsigned char dsa0;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dsa1 {
    unsigned char dsa1;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dra0 {
    unsigned short dra0;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_dra0l {
    unsigned char dra0l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dra0h {
    unsigned char dra0h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dra1 {
    unsigned short dra1;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_dra1l {
    unsigned char dra1l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dra1h {
    unsigned char dra1h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dbc0 {
    unsigned short dbc0;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_dbc0l {
    unsigned char dbc0l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dbc0h {
    unsigned char dbc0h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dbc1 {
    unsigned short dbc1;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_dbc1l {
    unsigned char dbc1l;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dbc1h {
    unsigned char dbc1h;
    struct {
        unsigned char bit0 :1;
        unsigned char bit1 :1;
        unsigned char bit2 :1;
        unsigned char bit3 :1;
        unsigned char bit4 :1;
        unsigned char bit5 :1;
        unsigned char bit6 :1;
        unsigned char bit7 :1;
    } BIT;
};
union un_dmc0 {
    unsigned char dmc0;
    struct {
        unsigned char :4;
        unsigned char dwait0 :1;
        unsigned char ds0 :1;
        unsigned char drs0 :1;
        unsigned char stg0 :1;
    } BIT;
};
union un_dmc1 {
    unsigned char dmc1;
    struct {
        unsigned char :4;
        unsigned char dwait1 :1;
        unsigned char ds1 :1;
        unsigned char drs1 :1;
        unsigned char stg1 :1;
    } BIT;
};
union un_drc0 {
    unsigned char drc0;
    struct {
        unsigned char dst0 :1;
        unsigned char :6;
        unsigned char den0 :1;
    } BIT;
};
union un_drc1 {
    unsigned char drc1;
    struct {
        unsigned char dst1 :1;
        unsigned char :6;
        unsigned char den1 :1;
    } BIT;
};
union un_if2 {
    unsigned short if2;
    struct {
        unsigned short tmif05 :1;
        unsigned short tmif06 :1;
        unsigned short tmif07 :1;
        unsigned short pif6 :1;
        unsigned short pif7 :1;
        unsigned short pif8 :1;
        unsigned short pif9 :1;
        unsigned short pif10 :1;
    } BIT;
};
union un_if2l {
    unsigned char if2l;
    struct {
        unsigned char tmif05 :1;
        unsigned char tmif06 :1;
        unsigned char tmif07 :1;
        unsigned char pif6 :1;
        unsigned char pif7 :1;
        unsigned char pif8 :1;
        unsigned char pif9 :1;
        unsigned char pif10 :1;
    } BIT;
};
union un_if2h {
    unsigned char if2h;
    struct {
        unsigned char pif11 :1;
        unsigned char tmif10 :1;
        unsigned char tmif11 :1;
        unsigned char tmif12 :1;
        unsigned char tmif13h :1;
        unsigned char mdif :1;
        unsigned char iicaif1 :1;
        unsigned char flif :1;
    } BIT;
};
union un_if3 {
    unsigned short if3;
    struct {
        unsigned short dmaif2 :1;
        unsigned short dmaif3 :1;
        unsigned short tmif14 :1;
        unsigned short tmif15 :1;
        unsigned short tmif16 :1;
        unsigned short tmif17 :1;
    } BIT;
};
union un_if3l {
    unsigned char if3l;
    struct {
        unsigned char dmaif2 :1;
        unsigned char dmaif3 :1;
        unsigned char tmif14 :1;
        unsigned char tmif15 :1;
        unsigned char tmif16 :1;
        unsigned char tmif17 :1;
    } BIT;
};
union un_mk2 {
    unsigned short mk2;
    struct {
        unsigned short tmmk05 :1;
        unsigned short tmmk06 :1;
        unsigned short tmmk07 :1;
        unsigned short pmk6 :1;
        unsigned short pmk7 :1;
        unsigned short pmk8 :1;
        unsigned short pmk9 :1;
        unsigned short pmk10 :1;
    } BIT;
};
union un_mk2l {
    unsigned char mk2l;
    struct {
        unsigned char tmmk05 :1;
        unsigned char tmmk06 :1;
        unsigned char tmmk07 :1;
        unsigned char pmk6 :1;
        unsigned char pmk7 :1;
        unsigned char pmk8 :1;
        unsigned char pmk9 :1;
        unsigned char pmk10 :1;
    } BIT;
};
union un_mk2h {
    unsigned char mk2h;
    struct {
        unsigned char pmk11 :1;
        unsigned char tmmk10 :1;
        unsigned char tmmk11 :1;
        unsigned char tmmk12 :1;
        unsigned char tmmk13h :1;
        unsigned char mdmk :1;
        unsigned char iicamk1 :1;
        unsigned char flmk :1;
    } BIT;
};
union un_mk3 {
    unsigned short mk3;
    struct {
        unsigned short dmamk2 :1;
        unsigned short dmamk3 :1;
        unsigned short tmmk14 :1;
        unsigned short tmmk15 :1;
        unsigned short tmmk16 :1;
        unsigned short tmmk17 :1;
    } BIT;
};
union un_mk3l {
    unsigned char mk3l;
    struct {
        unsigned char dmamk2 :1;
        unsigned char dmamk3 :1;
        unsigned char tmmk14 :1;
        unsigned char tmmk15 :1;
        unsigned char tmmk16 :1;
        unsigned char tmmk17 :1;
    } BIT;
};
union un_pr02 {
    unsigned short pr02;
    struct {
        unsigned short tmpr005 :1;
        unsigned short tmpr006 :1;
        unsigned short tmpr007 :1;
        unsigned short ppr06 :1;
        unsigned short ppr07 :1;
        unsigned short ppr08 :1;
        unsigned short ppr09 :1;
        unsigned short ppr010 :1;
    } BIT;
};
union un_pr02l {
    unsigned char pr02l;
    struct {
        unsigned char tmpr005 :1;
        unsigned char tmpr006 :1;
        unsigned char tmpr007 :1;
        unsigned char ppr06 :1;
        unsigned char ppr07 :1;
        unsigned char ppr08 :1;
        unsigned char ppr09 :1;
        unsigned char ppr010 :1;
    } BIT;
};
union un_pr02h {
    unsigned char pr02h;
    struct {
        unsigned char ppr011 :1;
        unsigned char tmpr010 :1;
        unsigned char tmpr011 :1;
        unsigned char tmpr012 :1;
        unsigned char tmpr013h :1;
        unsigned char mdpr0 :1;
        unsigned char iicapr01 :1;
        unsigned char flpr0 :1;
    } BIT;
};
union un_pr03 {
    unsigned short pr03;
    struct {
        unsigned short dmapr02 :1;
        unsigned short dmapr03 :1;
        unsigned short tmpr014 :1;
        unsigned short tmpr015 :1;
        unsigned short tmpr016 :1;
        unsigned short tmpr017 :1;
    } BIT;
};
union un_pr03l {
    unsigned char pr03l;
    struct {
        unsigned char dmapr02 :1;
        unsigned char dmapr03 :1;
        unsigned char tmpr014 :1;
        unsigned char tmpr015 :1;
        unsigned char tmpr016 :1;
        unsigned char tmpr017 :1;
    } BIT;
};
union un_pr12 {
    unsigned short pr12;
    struct {
        unsigned short tmpr105 :1;
        unsigned short tmpr106 :1;
        unsigned short tmpr107 :1;
        unsigned short ppr16 :1;
        unsigned short ppr17 :1;
        unsigned short ppr18 :1;
        unsigned short ppr19 :1;
        unsigned short ppr110 :1;
    } BIT;
};
union un_pr12l {
    unsigned char pr12l;
    struct {
        unsigned char tmpr105 :1;
        unsigned char tmpr106 :1;
        unsigned char tmpr107 :1;
        unsigned char ppr16 :1;
        unsigned char ppr17 :1;
        unsigned char ppr18 :1;
        unsigned char ppr19 :1;
        unsigned char ppr110 :1;
    } BIT;
};
union un_pr12h {
    unsigned char pr12h;
    struct {
        unsigned char ppr111 :1;
        unsigned char tmpr110 :1;
        unsigned char tmpr111 :1;
        unsigned char tmpr112 :1;
        unsigned char tmpr113h :1;
        unsigned char mdpr1 :1;
        unsigned char iicapr11 :1;
        unsigned char flpr1 :1;
    } BIT;
};
union un_pr13 {
    unsigned short pr13;
    struct {
        unsigned short dmapr12 :1;
        unsigned short dmapr13 :1;
        unsigned short tmpr114 :1;
        unsigned short tmpr115 :1;
        unsigned short tmpr116 :1;
        unsigned short tmpr117 :1;
    } BIT;
};
union un_pr13l {
    unsigned char pr13l;
    struct {
        unsigned char dmapr12 :1;
        unsigned char dmapr13 :1;
        unsigned char tmpr114 :1;
        unsigned char tmpr115 :1;
        unsigned char tmpr116 :1;
        unsigned char tmpr117 :1;
    } BIT;
};
union un_if0 {
    unsigned short if0;
    struct {
        unsigned short wdtiif :1;
        unsigned short lviif :1;
        unsigned short pif0 :1;
        unsigned short pif1 :1;
        unsigned short pif2 :1;
        unsigned short pif3 :1;
        unsigned short pif4 :1;
        unsigned short pif5 :1;
    } BIT;
};
union un_if0l {
    unsigned char if0l;
    struct {
        unsigned char wdtiif :1;
        unsigned char lviif :1;
        unsigned char pif0 :1;
        unsigned char pif1 :1;
        unsigned char pif2 :1;
        unsigned char pif3 :1;
        unsigned char pif4 :1;
        unsigned char pif5 :1;
    } BIT;
};
union un_if0h {
    unsigned char if0h;
    struct {
        unsigned char stif2 :1;
        unsigned char srif2 :1;
        unsigned char tmif11h :1;
        unsigned char dmaif0 :1;
        unsigned char dmaif1 :1;
        unsigned char stif0 :1;
        unsigned char srif0 :1;
        unsigned char tmif01h :1;
    } BIT;
};
union un_if1 {
    unsigned short if1;
    struct {
        unsigned short stif1 :1;
        unsigned short srif1 :1;
        unsigned short tmif03h :1;
        unsigned short iicaif0 :1;
        unsigned short tmif00 :1;
        unsigned short tmif01 :1;
        unsigned short tmif02 :1;
        unsigned short tmif03 :1;
    } BIT;
};
union un_if1l {
    unsigned char if1l;
    struct {
        unsigned char stif1 :1;
        unsigned char srif1 :1;
        unsigned char tmif03h :1;
        unsigned char iicaif0 :1;
        unsigned char tmif00 :1;
        unsigned char tmif01 :1;
        unsigned char tmif02 :1;
        unsigned char tmif03 :1;
    } BIT;
};
union un_if1h {
    unsigned char if1h;
    struct {
        unsigned char adif :1;
        unsigned char rtcif :1;
        unsigned char itif :1;
        unsigned char krif :1;
        unsigned char stif3 :1;
        unsigned char srif3 :1;
        unsigned char tmif13 :1;
        unsigned char tmif04 :1;
    } BIT;
};
union un_mk0 {
    unsigned short mk0;
    struct {
        unsigned short wdtimk :1;
        unsigned short lvimk :1;
        unsigned short pmk0 :1;
        unsigned short pmk1 :1;
        unsigned short pmk2 :1;
        unsigned short pmk3 :1;
        unsigned short pmk4 :1;
        unsigned short pmk5 :1;
    } BIT;
};
union un_mk0l {
    unsigned char mk0l;
    struct {
        unsigned char wdtimk :1;
        unsigned char lvimk :1;
        unsigned char pmk0 :1;
        unsigned char pmk1 :1;
        unsigned char pmk2 :1;
        unsigned char pmk3 :1;
        unsigned char pmk4 :1;
        unsigned char pmk5 :1;
    } BIT;
};
union un_mk0h {
    unsigned char mk0h;
    struct {
        unsigned char stmk2 :1;
        unsigned char srmk2 :1;
        unsigned char tmmk11h :1;
        unsigned char dmamk0 :1;
        unsigned char dmamk1 :1;
        unsigned char stmk0 :1;
        unsigned char srmk0 :1;
        unsigned char tmmk01h :1;
    } BIT;
};
union un_mk1 {
    unsigned short mk1;
    struct {
        unsigned short stmk1 :1;
        unsigned short srmk1 :1;
        unsigned short tmmk03h :1;
        unsigned short iicamk0 :1;
        unsigned short tmmk00 :1;
        unsigned short tmmk01 :1;
        unsigned short tmmk02 :1;
        unsigned short tmmk03 :1;
    } BIT;
};
union un_mk1l {
    unsigned char mk1l;
    struct {
        unsigned char stmk1 :1;
        unsigned char srmk1 :1;
        unsigned char tmmk03h :1;
        unsigned char iicamk0 :1;
        unsigned char tmmk00 :1;
        unsigned char tmmk01 :1;
        unsigned char tmmk02 :1;
        unsigned char tmmk03 :1;
    } BIT;
};
union un_mk1h {
    unsigned char mk1h;
    struct {
        unsigned char admk :1;
        unsigned char rtcmk :1;
        unsigned char itmk :1;
        unsigned char krmk :1;
        unsigned char stmk3 :1;
        unsigned char srmk3 :1;
        unsigned char tmmk13 :1;
        unsigned char tmmk04 :1;
    } BIT;
};
union un_pr00 {
    unsigned short pr00;
    struct {
        unsigned short wdtipr0 :1;
        unsigned short lvipr0 :1;
        unsigned short ppr00 :1;
        unsigned short ppr01 :1;
        unsigned short ppr02 :1;
        unsigned short ppr03 :1;
        unsigned short ppr04 :1;
        unsigned short ppr05 :1;
    } BIT;
};
union un_pr00l {
    unsigned char pr00l;
    struct {
        unsigned char wdtipr0 :1;
        unsigned char lvipr0 :1;
        unsigned char ppr00 :1;
        unsigned char ppr01 :1;
        unsigned char ppr02 :1;
        unsigned char ppr03 :1;
        unsigned char ppr04 :1;
        unsigned char ppr05 :1;
    } BIT;
};
union un_pr00h {
    unsigned char pr00h;
    struct {
        unsigned char stpr02 :1;
        unsigned char srpr02 :1;
        unsigned char tmpr011h :1;
        unsigned char dmapr00 :1;
        unsigned char dmapr01 :1;
        unsigned char stpr00 :1;
        unsigned char srpr00 :1;
        unsigned char tmpr001h :1;
    } BIT;
};
union un_pr01 {
    unsigned short pr01;
    struct {
        unsigned short stpr01 :1;
        unsigned short srpr01 :1;
        unsigned short tmpr003h :1;
        unsigned short iicapr00 :1;
        unsigned short tmpr000 :1;
        unsigned short tmpr001 :1;
        unsigned short tmpr002 :1;
        unsigned short tmpr003 :1;
    } BIT;
};
union un_pr01l {
    unsigned char pr01l;
    struct {
        unsigned char stpr01 :1;
        unsigned char srpr01 :1;
        unsigned char tmpr003h :1;
        unsigned char iicapr00 :1;
        unsigned char tmpr000 :1;
        unsigned char tmpr001 :1;
        unsigned char tmpr002 :1;
        unsigned char tmpr003 :1;
    } BIT;
};
union un_pr01h {
    unsigned char pr01h;
    struct {
        unsigned char adpr0 :1;
        unsigned char rtcpr0 :1;
        unsigned char itpr0 :1;
        unsigned char krpr0 :1;
        unsigned char stpr03 :1;
        unsigned char srpr03 :1;
        unsigned char tmpr013 :1;
        unsigned char tmpr004 :1;
    } BIT;
};
union un_pr10 {
    unsigned short pr10;
    struct {
        unsigned short wdtipr1 :1;
        unsigned short lvipr1 :1;
        unsigned short ppr10 :1;
        unsigned short ppr11 :1;
        unsigned short ppr12 :1;
        unsigned short ppr13 :1;
        unsigned short ppr14 :1;
        unsigned short ppr15 :1;
    } BIT;
};
union un_pr10l {
    unsigned char pr10l;
    struct {
        unsigned char wdtipr1 :1;
        unsigned char lvipr1 :1;
        unsigned char ppr10 :1;
        unsigned char ppr11 :1;
        unsigned char ppr12 :1;
        unsigned char ppr13 :1;
        unsigned char ppr14 :1;
        unsigned char ppr15 :1;
    } BIT;
};
union un_pr10h {
    unsigned char pr10h;
    struct {
        unsigned char stpr12 :1;
        unsigned char srpr12 :1;
        unsigned char tmpr111h :1;
        unsigned char dmapr10 :1;
        unsigned char dmapr11 :1;
        unsigned char stpr10 :1;
        unsigned char srpr10 :1;
        unsigned char tmpr101h :1;
    } BIT;
};
union un_pr11 {
    unsigned short pr11;
    struct {
        unsigned short stpr11 :1;
        unsigned short srpr11 :1;
        unsigned short tmpr103h :1;
        unsigned short iicapr10 :1;
        unsigned short tmpr100 :1;
        unsigned short tmpr101 :1;
        unsigned short tmpr102 :1;
        unsigned short tmpr103 :1;
    } BIT;
};
union un_pr11l {
    unsigned char pr11l;
    struct {
        unsigned char stpr11 :1;
        unsigned char srpr11 :1;
        unsigned char tmpr103h :1;
        unsigned char iicapr10 :1;
        unsigned char tmpr100 :1;
        unsigned char tmpr101 :1;
        unsigned char tmpr102 :1;
        unsigned char tmpr103 :1;
    } BIT;
};
union un_pr11h {
    unsigned char pr11h;
    struct {
        unsigned char adpr1 :1;
        unsigned char rtcpr1 :1;
        unsigned char itpr1 :1;
        unsigned char krpr1 :1;
        unsigned char stpr13 :1;
        unsigned char srpr13 :1;
        unsigned char tmpr113 :1;
        unsigned char tmpr104 :1;
    } BIT;
};
union un_mdal {
    unsigned short mdal;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_mula {
    unsigned short mula;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_mdah {
    unsigned short mdah;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_mulb {
    unsigned short mulb;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_mdbh {
    unsigned short mdbh;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_muloh {
    unsigned short muloh;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_mdbl {
    unsigned short mdbl;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_mulol {
    unsigned short mulol;
    struct {
        unsigned short bit0 :1;
        unsigned short bit1 :1;
        unsigned short bit2 :1;
        unsigned short bit3 :1;
        unsigned short bit4 :1;
        unsigned short bit5 :1;
        unsigned short bit6 :1;
        unsigned short bit7 :1;
        unsigned short bit8 :1;
        unsigned short bit9 :1;
        unsigned short bit10 :1;
        unsigned short bit11 :1;
        unsigned short bit12 :1;
        unsigned short bit13 :1;
        unsigned short bit14 :1;
        unsigned short bit15 :1;
    } BIT;
};
union un_pmc {
    unsigned char pmc;
    struct {
        unsigned char maa :1;
    } BIT;
};

#define P0 (*(volatile union un_p0 *)0xFFF00)
#define P1 (*(volatile union un_p1 *)0xFFF01)
#define P2 (*(volatile union un_p2 *)0xFFF02)
#define P3 (*(volatile union un_p3 *)0xFFF03)
#define P4 (*(volatile union un_p4 *)0xFFF04)
#define P5 (*(volatile union un_p5 *)0xFFF05)
#define P6 (*(volatile union un_p6 *)0xFFF06)
#define P7 (*(volatile union un_p7 *)0xFFF07)
#define P8 (*(volatile union un_p8 *)0xFFF08)
#define P9 (*(volatile union un_p9 *)0xFFF09)
#define P10 (*(volatile union un_p10 *)0xFFF0A)
#define P11 (*(volatile union un_p11 *)0xFFF0B)
#define P12 (*(volatile union un_p12 *)0xFFF0C)
#define P13 (*(volatile union un_p13 *)0xFFF0D)
#define P14 (*(volatile union un_p14 *)0xFFF0E)
#define P15 (*(volatile union un_p15 *)0xFFF0F)
#define SDR00 (*(volatile union un_sdr00 *)0xFFF10)
#define SIO00 (*(volatile union un_sio00 *)0xFFF10)
#define TXD0 (*(volatile union un_txd0 *)0xFFF10)
#define SDR01 (*(volatile union un_sdr01 *)0xFFF12)
#define RXD0 (*(volatile union un_rxd0 *)0xFFF12)
#define SIO01 (*(volatile union un_sio01 *)0xFFF12)
#define SDR12 (*(volatile union un_sdr12 *)0xFFF14)
#define SIO30 (*(volatile union un_sio30 *)0xFFF14)
#define TXD3 (*(volatile union un_txd3 *)0xFFF14)
#define SDR13 (*(volatile union un_sdr13 *)0xFFF16)
#define RXD3 (*(volatile union un_rxd3 *)0xFFF16)
#define SIO31 (*(volatile union un_sio31 *)0xFFF16)
#define TDR00 (*(volatile union un_tdr00 *)0xFFF18)
#define TDR01 (*(volatile union un_tdr01 *)0xFFF1A)
#define TDR01L (*(volatile union un_tdr01l *)0xFFF1A)
#define TDR01H (*(volatile union un_tdr01h *)0xFFF1B)
#define ADCR (*(volatile union un_adcr *)0xFFF1E)
#define ADCRH (*(volatile union un_adcrh *)0xFFF1F)
#define PM0 (*(volatile union un_pm0 *)0xFFF20)
#define PM1 (*(volatile union un_pm1 *)0xFFF21)
#define PM2 (*(volatile union un_pm2 *)0xFFF22)
#define PM3 (*(volatile union un_pm3 *)0xFFF23)
#define PM4 (*(volatile union un_pm4 *)0xFFF24)
#define PM5 (*(volatile union un_pm5 *)0xFFF25)
#define PM6 (*(volatile union un_pm6 *)0xFFF26)
#define PM7 (*(volatile union un_pm7 *)0xFFF27)
#define PM8 (*(volatile union un_pm8 *)0xFFF28)
#define PM9 (*(volatile union un_pm9 *)0xFFF29)
#define PM10 (*(volatile union un_pm10 *)0xFFF2A)
#define PM11 (*(volatile union un_pm11 *)0xFFF2B)
#define PM12 (*(volatile union un_pm12 *)0xFFF2C)
#define PM14 (*(volatile union un_pm14 *)0xFFF2E)
#define PM15 (*(volatile union un_pm15 *)0xFFF2F)
#define ADM0 (*(volatile union un_adm0 *)0xFFF30)
#define ADS (*(volatile union un_ads *)0xFFF31)
#define ADM1 (*(volatile union un_adm1 *)0xFFF32)
#define KRM (*(volatile union un_krm *)0xFFF37)
#define EGP0 (*(volatile union un_egp0 *)0xFFF38)
#define EGN0 (*(volatile union un_egn0 *)0xFFF39)
#define EGP1 (*(volatile union un_egp1 *)0xFFF3A)
#define EGN1 (*(volatile union un_egn1 *)0xFFF3B)
#define SDR02 (*(volatile union un_sdr02 *)0xFFF44)
#define SIO10 (*(volatile union un_sio10 *)0xFFF44)
#define TXD1 (*(volatile union un_txd1 *)0xFFF44)
#define SDR03 (*(volatile union un_sdr03 *)0xFFF46)
#define RXD1 (*(volatile union un_rxd1 *)0xFFF46)
#define SIO11 (*(volatile union un_sio11 *)0xFFF46)
#define SDR10 (*(volatile union un_sdr10 *)0xFFF48)
#define SIO20 (*(volatile union un_sio20 *)0xFFF48)
#define TXD2 (*(volatile union un_txd2 *)0xFFF48)
#define SDR11 (*(volatile union un_sdr11 *)0xFFF4A)
#define RXD2 (*(volatile union un_rxd2 *)0xFFF4A)
#define SIO21 (*(volatile union un_sio21 *)0xFFF4A)
#define IICA0 (*(volatile union un_iica0 *)0xFFF50)
#define IICS0 (*(volatile union un_iics0 *)0xFFF51)
#define IICF0 (*(volatile union un_iicf0 *)0xFFF52)
#define IICA1 (*(volatile union un_iica1 *)0xFFF54)
#define IICS1 (*(volatile union un_iics1 *)0xFFF55)
#define IICF1 (*(volatile union un_iicf1 *)0xFFF56)
#define TDR02 (*(volatile union un_tdr02 *)0xFFF64)
#define TDR03 (*(volatile union un_tdr03 *)0xFFF66)
#define TDR03L (*(volatile union un_tdr03l *)0xFFF66)
#define TDR03H (*(volatile union un_tdr03h *)0xFFF67)
#define TDR04 (*(volatile union un_tdr04 *)0xFFF68)
#define TDR05 (*(volatile union un_tdr05 *)0xFFF6A)
#define TDR06 (*(volatile union un_tdr06 *)0xFFF6C)
#define TDR07 (*(volatile union un_tdr07 *)0xFFF6E)
#define TDR10 (*(volatile union un_tdr10 *)0xFFF70)
#define TDR11 (*(volatile union un_tdr11 *)0xFFF72)
#define TDR11L (*(volatile union un_tdr11l *)0xFFF72)
#define TDR11H (*(volatile union un_tdr11h *)0xFFF73)
#define TDR12 (*(volatile union un_tdr12 *)0xFFF74)
#define TDR13 (*(volatile union un_tdr13 *)0xFFF76)
#define TDR13L (*(volatile union un_tdr13l *)0xFFF76)
#define TDR13H (*(volatile union un_tdr13h *)0xFFF77)
#define TDR14 (*(volatile union un_tdr14 *)0xFFF78)
#define TDR15 (*(volatile union un_tdr15 *)0xFFF7A)
#define TDR16 (*(volatile union un_tdr16 *)0xFFF7C)
#define TDR17 (*(volatile union un_tdr17 *)0xFFF7E)
#define FLPMC (*(volatile union un_flpmc *)0xFFF80)
#define FLARS (*(volatile union un_flars *)0xFFF81)
#define FLAPL (*(volatile union un_flapl *)0xFFF82)
#define FLAPH (*(volatile union un_flaph *)0xFFF84)
#define FSSQ (*(volatile union un_fssq *)0xFFF85)
#define FLSEDL (*(volatile union un_flsedl *)0xFFF86)
#define FLSEDH (*(volatile union un_flsedh *)0xFFF88)
#define FLRST (*(volatile union un_flrst *)0xFFF89)
#define FSASTL (*(volatile union un_fsastl *)0xFFF8A)
#define FSASTH (*(volatile union un_fsasth *)0xFFF8B)
#define FLWL (*(volatile union un_flwl *)0xFFF8C)
#define FLWH (*(volatile union un_flwh *)0xFFF8E)
#define ITMC (*(volatile union un_itmc *)0xFFF90)
#define SEC (*(volatile union un_sec *)0xFFF92)
#define MIN (*(volatile union un_min *)0xFFF93)
#define HOUR (*(volatile union un_hour *)0xFFF94)
#define WEEK (*(volatile union un_week *)0xFFF95)
#define DAY (*(volatile union un_day *)0xFFF96)
#define MONTH (*(volatile union un_month *)0xFFF97)
#define YEAR (*(volatile union un_year *)0xFFF98)
#define SUBCUD (*(volatile union un_subcud *)0xFFF99)
#define ALARMWM (*(volatile union un_alarmwm *)0xFFF9A)
#define ALARMWH (*(volatile union un_alarmwh *)0xFFF9B)
#define ALARMWW (*(volatile union un_alarmww *)0xFFF9C)
#define RTCC0 (*(volatile union un_rtcc0 *)0xFFF9D)
#define RTCC1 (*(volatile union un_rtcc1 *)0xFFF9E)
#define CMC (*(volatile union un_cmc *)0xFFFA0)
#define CSC (*(volatile union un_csc *)0xFFFA1)
#define OSTC (*(volatile union un_ostc *)0xFFFA2)
#define OSTS (*(volatile union un_osts *)0xFFFA3)
#define CKC (*(volatile union un_ckc *)0xFFFA4)
#define CKS0 (*(volatile union un_cks0 *)0xFFFA5)
#define CKS1 (*(volatile union un_cks1 *)0xFFFA6)
#define RESF (*(volatile union un_resf *)0xFFFA8)
#define LVIM (*(volatile union un_lvim *)0xFFFA9)
#define LVIS (*(volatile union un_lvis *)0xFFFAA)
#define WDTE (*(volatile union un_wdte *)0xFFFAB)
#define CRCIN (*(volatile union un_crcin *)0xFFFAC)
#define RXB (*(volatile union un_rxb *)0xFFFAD)
#define TXS (*(volatile union un_txs *)0xFFFAD)
#define MONSTA0 (*(volatile union un_monsta0 *)0xFFFAE)
#define ASIM (*(volatile union un_asim *)0xFFFAF)
#define DSA0 (*(volatile union un_dsa0 *)0xFFFB0)
#define DSA1 (*(volatile union un_dsa1 *)0xFFFB1)
#define DRA0 (*(volatile union un_dra0 *)0xFFFB2)
#define DRA0L (*(volatile union un_dra0l *)0xFFFB2)
#define DRA0H (*(volatile union un_dra0h *)0xFFFB3)
#define DRA1 (*(volatile union un_dra1 *)0xFFFB4)
#define DRA1L (*(volatile union un_dra1l *)0xFFFB4)
#define DRA1H (*(volatile union un_dra1h *)0xFFFB5)
#define DBC0 (*(volatile union un_dbc0 *)0xFFFB6)
#define DBC0L (*(volatile union un_dbc0l *)0xFFFB6)
#define DBC0H (*(volatile union un_dbc0h *)0xFFFB7)
#define DBC1 (*(volatile union un_dbc1 *)0xFFFB8)
#define DBC1L (*(volatile union un_dbc1l *)0xFFFB8)
#define DBC1H (*(volatile union un_dbc1h *)0xFFFB9)
#define DMC0 (*(volatile union un_dmc0 *)0xFFFBA)
#define DMC1 (*(volatile union un_dmc1 *)0xFFFBB)
#define DRC0 (*(volatile union un_drc0 *)0xFFFBC)
#define DRC1 (*(volatile union un_drc1 *)0xFFFBD)
#define IF2 (*(volatile union un_if2 *)0xFFFD0)
#define IF2L (*(volatile union un_if2l *)0xFFFD0)
#define IF2H (*(volatile union un_if2h *)0xFFFD1)
#define IF3 (*(volatile union un_if3 *)0xFFFD2)
#define IF3L (*(volatile union un_if3l *)0xFFFD2)
#define MK2 (*(volatile union un_mk2 *)0xFFFD4)
#define MK2L (*(volatile union un_mk2l *)0xFFFD4)
#define MK2H (*(volatile union un_mk2h *)0xFFFD5)
#define MK3 (*(volatile union un_mk3 *)0xFFFD6)
#define MK3L (*(volatile union un_mk3l *)0xFFFD6)
#define PR02 (*(volatile union un_pr02 *)0xFFFD8)
#define PR02L (*(volatile union un_pr02l *)0xFFFD8)
#define PR02H (*(volatile union un_pr02h *)0xFFFD9)
#define PR03 (*(volatile union un_pr03 *)0xFFFDA)
#define PR03L (*(volatile union un_pr03l *)0xFFFDA)
#define PR12 (*(volatile union un_pr12 *)0xFFFDC)
#define PR12L (*(volatile union un_pr12l *)0xFFFDC)
#define PR12H (*(volatile union un_pr12h *)0xFFFDD)
#define PR13 (*(volatile union un_pr13 *)0xFFFDE)
#define PR13L (*(volatile union un_pr13l *)0xFFFDE)
#define IF0 (*(volatile union un_if0 *)0xFFFE0)
#define IF0L (*(volatile union un_if0l *)0xFFFE0)
#define IF0H (*(volatile union un_if0h *)0xFFFE1)
#define IF1 (*(volatile union un_if1 *)0xFFFE2)
#define IF1L (*(volatile union un_if1l *)0xFFFE2)
#define IF1H (*(volatile union un_if1h *)0xFFFE3)
#define MK0 (*(volatile union un_mk0 *)0xFFFE4)
#define MK0L (*(volatile union un_mk0l *)0xFFFE4)
#define MK0H (*(volatile union un_mk0h *)0xFFFE5)
#define MK1 (*(volatile union un_mk1 *)0xFFFE6)
#define MK1L (*(volatile union un_mk1l *)0xFFFE6)
#define MK1H (*(volatile union un_mk1h *)0xFFFE7)
#define PR00 (*(volatile union un_pr00 *)0xFFFE8)
#define PR00L (*(volatile union un_pr00l *)0xFFFE8)
#define PR00H (*(volatile union un_pr00h *)0xFFFE9)
#define PR01 (*(volatile union un_pr01 *)0xFFFEA)
#define PR01L (*(volatile union un_pr01l *)0xFFFEA)
#define PR01H (*(volatile union un_pr01h *)0xFFFEB)
#define PR10 (*(volatile union un_pr10 *)0xFFFEC)
#define PR10L (*(volatile union un_pr10l *)0xFFFEC)
#define PR10H (*(volatile union un_pr10h *)0xFFFED)
#define PR11 (*(volatile union un_pr11 *)0xFFFEE)
#define PR11L (*(volatile union un_pr11l *)0xFFFEE)
#define PR11H (*(volatile union un_pr11h *)0xFFFEF)
#define MDAL (*(volatile union un_mdal *)0xFFFF0)
#define MULA (*(volatile union un_mula *)0xFFFF0)
#define MDAH (*(volatile union un_mdah *)0xFFFF2)
#define MULB (*(volatile union un_mulb *)0xFFFF2)
#define MDBH (*(volatile union un_mdbh *)0xFFFF4)
#define MULOH (*(volatile union un_muloh *)0xFFFF4)
#define MDBL (*(volatile union un_mdbl *)0xFFFF6)
#define MULOL (*(volatile union un_mulol *)0xFFFF6)
#define PMC (*(volatile union un_pmc *)0xFFFFE)

/*
 Sfr bits
 */
#define ADCE ADM0.BIT.adce
#define ADCS ADM0.BIT.adcs
#define SPD0 IICS0.BIT.spd0
#define STD0 IICS0.BIT.std0
#define ACKD0 IICS0.BIT.ackd0
#define TRC0 IICS0.BIT.trc0
#define COI0 IICS0.BIT.coi0
#define EXC0 IICS0.BIT.exc0
#define ALD0 IICS0.BIT.ald0
#define MSTS0 IICS0.BIT.msts0
#define IICRSV0 IICF0.BIT.iicrsv0
#define STCEN0 IICF0.BIT.stcen0
#define IICBSY0 IICF0.BIT.iicbsy0
#define STCF0 IICF0.BIT.stcf0
#define SPD1 IICS1.BIT.spd1
#define STD1 IICS1.BIT.std1
#define ACKD1 IICS1.BIT.ackd1
#define TRC1 IICS1.BIT.trc1
#define COI1 IICS1.BIT.coi1
#define EXC1 IICS1.BIT.exc1
#define ALD1 IICS1.BIT.ald1
#define MSTS1 IICS1.BIT.msts1
#define IICRSV1 IICF1.BIT.iicrsv1
#define STCEN1 IICF1.BIT.stcen1
#define IICBSY1 IICF1.BIT.iicbsy1
#define STCF1 IICF1.BIT.stcf1
#define FSSTP FSSQ.BIT.fsstp
#define SQST FSSQ.BIT.sqst
#define SQEND FSASTH.BIT.sqend
#define ESQEND FSASTH.BIT.esqend
#define RCLOE1 RTCC0.BIT.rcloe1
#define RTCE RTCC0.BIT.rtce
#define RWAIT RTCC1.BIT.rwait
#define RWST RTCC1.BIT.rwst
#define RIFG RTCC1.BIT.rifg
#define WAFG RTCC1.BIT.wafg
#define WALIE RTCC1.BIT.walie
#define WALE RTCC1.BIT.wale
#define HIOSTOP CSC.BIT.hiostop
#define XTSTOP CSC.BIT.xtstop
#define MSTOP CSC.BIT.mstop
#define SDIV CKC.BIT.sdiv
#define MCM0 CKC.BIT.mcm0
#define MCS CKC.BIT.mcs
#define CSS CKC.BIT.css
#define CLS CKC.BIT.cls
#define PCLOE0 CKS0.BIT.pcloe0
#define PCLOE1 CKS1.BIT.pcloe1
#define LVIF LVIM.BIT.lvif
#define LVIOMSK LVIM.BIT.lviomsk
#define LVISEN LVIM.BIT.lvisen
#define LVILV LVIS.BIT.lvilv
#define LVIMD LVIS.BIT.lvimd
#define DWAIT0 DMC0.BIT.dwait0
#define DS0 DMC0.BIT.ds0
#define DRS0 DMC0.BIT.drs0
#define STG0 DMC0.BIT.stg0
#define DWAIT1 DMC1.BIT.dwait1
#define DS1 DMC1.BIT.ds1
#define DRS1 DMC1.BIT.drs1
#define STG1 DMC1.BIT.stg1
#define DST0 DRC0.BIT.dst0
#define DEN0 DRC0.BIT.den0
#define DST1 DRC1.BIT.dst1
#define DEN1 DRC1.BIT.den1
#define TMIF05 IF2.BIT.tmif05
#define TMIF06 IF2.BIT.tmif06
#define TMIF07 IF2.BIT.tmif07
#define PIF6 IF2.BIT.pif6
#define PIF7 IF2.BIT.pif7
#define PIF8 IF2.BIT.pif8
#define PIF9 IF2.BIT.pif9
#define PIF10 IF2.BIT.pif10
#define PIF11 IF2H.BIT.pif11
#define TMIF10 IF2H.BIT.tmif10
#define TMIF11 IF2H.BIT.tmif11
#define TMIF12 IF2H.BIT.tmif12
#define SREIF3 IF2H.BIT.tmif13h
#define TMIF13H IF2H.BIT.tmif13h
#define MDIF IF2H.BIT.mdif
#define IICAIF1 IF2H.BIT.iicaif1
#define FLIF IF2H.BIT.flif
#define DMAIF2 IF3.BIT.dmaif2
#define DMAIF3 IF3.BIT.dmaif3
#define TMIF14 IF3.BIT.tmif14
#define TMIF15 IF3.BIT.tmif15
#define TMIF16 IF3.BIT.tmif16
#define TMIF17 IF3.BIT.tmif17
#define TMMK05 MK2.BIT.tmmk05
#define TMMK06 MK2.BIT.tmmk06
#define TMMK07 MK2.BIT.tmmk07
#define PMK6 MK2.BIT.pmk6
#define PMK7 MK2.BIT.pmk7
#define PMK8 MK2.BIT.pmk8
#define PMK9 MK2.BIT.pmk9
#define PMK10 MK2.BIT.pmk10
#define PMK11 MK2H.BIT.pmk11
#define TMMK10 MK2H.BIT.tmmk10
#define TMMK11 MK2H.BIT.tmmk11
#define TMMK12 MK2H.BIT.tmmk12
#define SREMK3 MK2H.BIT.tmmk13h
#define TMMK13H MK2H.BIT.tmmk13h
#define MDMK MK2H.BIT.mdmk
#define IICAMK1 MK2H.BIT.iicamk1
#define FLMK MK2H.BIT.flmk
#define DMAMK2 MK3.BIT.dmamk2
#define DMAMK3 MK3.BIT.dmamk3
#define TMMK14 MK3.BIT.tmmk14
#define TMMK15 MK3.BIT.tmmk15
#define TMMK16 MK3.BIT.tmmk16
#define TMMK17 MK3.BIT.tmmk17
#define TMPR005 PR02.BIT.tmpr005
#define TMPR006 PR02.BIT.tmpr006
#define TMPR007 PR02.BIT.tmpr007
#define PPR06 PR02.BIT.ppr06
#define PPR07 PR02.BIT.ppr07
#define PPR08 PR02.BIT.ppr08
#define PPR09 PR02.BIT.ppr09
#define PPR010 PR02.BIT.ppr010
#define PPR011 PR02H.BIT.ppr011
#define TMPR010 PR02H.BIT.tmpr010
#define TMPR011 PR02H.BIT.tmpr011
#define TMPR012 PR02H.BIT.tmpr012
#define SREPR03 PR02H.BIT.tmpr013h
#define TMPR013H PR02H.BIT.tmpr013h
#define MDPR0 PR02H.BIT.mdpr0
#define IICAPR01 PR02H.BIT.iicapr01
#define FLPR0 PR02H.BIT.flpr0
#define DMAPR02 PR03.BIT.dmapr02
#define DMAPR03 PR03.BIT.dmapr03
#define TMPR014 PR03.BIT.tmpr014
#define TMPR015 PR03.BIT.tmpr015
#define TMPR016 PR03.BIT.tmpr016
#define TMPR017 PR03.BIT.tmpr017
#define TMPR105 PR12.BIT.tmpr105
#define TMPR106 PR12.BIT.tmpr106
#define TMPR107 PR12.BIT.tmpr107
#define PPR16 PR12.BIT.ppr16
#define PPR17 PR12.BIT.ppr17
#define PPR18 PR12.BIT.ppr18
#define PPR19 PR12.BIT.ppr19
#define PPR110 PR12.BIT.ppr110
#define PPR111 PR12H.BIT.ppr111
#define TMPR110 PR12H.BIT.tmpr110
#define TMPR111 PR12H.BIT.tmpr111
#define TMPR112 PR12H.BIT.tmpr112
#define SREPR13 PR12H.BIT.tmpr113h
#define TMPR113H PR12H.BIT.tmpr113h
#define MDPR1 PR12H.BIT.mdpr1
#define IICAPR11 PR12H.BIT.iicapr11
#define FLPR1 PR12H.BIT.flpr1
#define DMAPR12 PR13.BIT.dmapr12
#define DMAPR13 PR13.BIT.dmapr13
#define TMPR114 PR13.BIT.tmpr114
#define TMPR115 PR13.BIT.tmpr115
#define TMPR116 PR13.BIT.tmpr116
#define TMPR117 PR13.BIT.tmpr117
#define WDTIIF IF0.BIT.wdtiif
#define LVIIF IF0.BIT.lviif
#define PIF0 IF0.BIT.pif0
#define PIF1 IF0.BIT.pif1
#define PIF2 IF0.BIT.pif2
#define PIF3 IF0.BIT.pif3
#define PIF4 IF0.BIT.pif4
#define PIF5 IF0.BIT.pif5
#define CSIIF20 IF0H.BIT.stif2
#define IICIF20 IF0H.BIT.stif2
#define STIF2 IF0H.BIT.stif2
#define CSIIF21 IF0H.BIT.srif2
#define IICIF21 IF0H.BIT.srif2
#define SRIF2 IF0H.BIT.srif2
#define SREIF2 IF0H.BIT.tmif11h
#define TMIF11H IF0H.BIT.tmif11h
#define DMAIF0 IF0H.BIT.dmaif0
#define DMAIF1 IF0H.BIT.dmaif1
#define CSIIF00 IF0H.BIT.stif0
#define IICIF00 IF0H.BIT.stif0
#define STIF0 IF0H.BIT.stif0
#define CSIIF01 IF0H.BIT.srif0
#define IICIF01 IF0H.BIT.srif0
#define SRIF0 IF0H.BIT.srif0
#define SREIF0 IF0H.BIT.tmif01h
#define TMIF01H IF0H.BIT.tmif01h
#define CSIIF10 IF1.BIT.stif1
#define IICIF10 IF1.BIT.stif1
#define STIF1 IF1.BIT.stif1
#define CSIIF11 IF1.BIT.srif1
#define IICIF11 IF1.BIT.srif1
#define SRIF1 IF1.BIT.srif1
#define SREIF1 IF1.BIT.tmif03h
#define TMIF03H IF1.BIT.tmif03h
#define IICAIF0 IF1.BIT.iicaif0
#define TMIF00 IF1.BIT.tmif00
#define TMIF01 IF1.BIT.tmif01
#define TMIF02 IF1.BIT.tmif02
#define TMIF03 IF1.BIT.tmif03
#define ADIF IF1H.BIT.adif
#define RTCIF IF1H.BIT.rtcif
#define ITIF IF1H.BIT.itif
#define KRIF IF1H.BIT.krif
#define CSIIF30 IF1H.BIT.stif3
#define IICIF30 IF1H.BIT.stif3
#define STIF3 IF1H.BIT.stif3
#define CSIIF31 IF1H.BIT.srif3
#define IICIF31 IF1H.BIT.srif3
#define SRIF3 IF1H.BIT.srif3
#define TMIF13 IF1H.BIT.tmif13
#define TMIF04 IF1H.BIT.tmif04
#define WDTIMK MK0.BIT.wdtimk
#define LVIMK MK0.BIT.lvimk
#define PMK0 MK0.BIT.pmk0
#define PMK1 MK0.BIT.pmk1
#define PMK2 MK0.BIT.pmk2
#define PMK3 MK0.BIT.pmk3
#define PMK4 MK0.BIT.pmk4
#define PMK5 MK0.BIT.pmk5
#define CSIMK20 MK0H.BIT.stmk2
#define IICMK20 MK0H.BIT.stmk2
#define STMK2 MK0H.BIT.stmk2
#define CSIMK21 MK0H.BIT.srmk2
#define IICMK21 MK0H.BIT.srmk2
#define SRMK2 MK0H.BIT.srmk2
#define SREMK2 MK0H.BIT.tmmk11h
#define TMMK11H MK0H.BIT.tmmk11h
#define DMAMK0 MK0H.BIT.dmamk0
#define DMAMK1 MK0H.BIT.dmamk1
#define CSIMK00 MK0H.BIT.stmk0
#define IICMK00 MK0H.BIT.stmk0
#define STMK0 MK0H.BIT.stmk0
#define CSIMK01 MK0H.BIT.srmk0
#define IICMK01 MK0H.BIT.srmk0
#define SRMK0 MK0H.BIT.srmk0
#define SREMK0 MK0H.BIT.tmmk01h
#define TMMK01H MK0H.BIT.tmmk01h
#define CSIMK10 MK1.BIT.stmk1
#define IICMK10 MK1.BIT.stmk1
#define STMK1 MK1.BIT.stmk1
#define CSIMK11 MK1.BIT.srmk1
#define IICMK11 MK1.BIT.srmk1
#define SRMK1 MK1.BIT.srmk1
#define SREMK1 MK1.BIT.tmmk03h
#define TMMK03H MK1.BIT.tmmk03h
#define IICAMK0 MK1.BIT.iicamk0
#define TMMK00 MK1.BIT.tmmk00
#define TMMK01 MK1.BIT.tmmk01
#define TMMK02 MK1.BIT.tmmk02
#define TMMK03 MK1.BIT.tmmk03
#define ADMK MK1H.BIT.admk
#define RTCMK MK1H.BIT.rtcmk
#define ITMK MK1H.BIT.itmk
#define KRMK MK1H.BIT.krmk
#define CSIMK30 MK1H.BIT.stmk3
#define IICMK30 MK1H.BIT.stmk3
#define STMK3 MK1H.BIT.stmk3
#define CSIMK31 MK1H.BIT.srmk3
#define IICMK31 MK1H.BIT.srmk3
#define SRMK3 MK1H.BIT.srmk3
#define TMMK13 MK1H.BIT.tmmk13
#define TMMK04 MK1H.BIT.tmmk04
#define WDTIPR0 PR00.BIT.wdtipr0
#define LVIPR0 PR00.BIT.lvipr0
#define PPR00 PR00.BIT.ppr00
#define PPR01 PR00.BIT.ppr01
#define PPR02 PR00.BIT.ppr02
#define PPR03 PR00.BIT.ppr03
#define PPR04 PR00.BIT.ppr04
#define PPR05 PR00.BIT.ppr05
#define CSIPR020 PR00H.BIT.stpr02
#define IICPR020 PR00H.BIT.stpr02
#define STPR02 PR00H.BIT.stpr02
#define CSIPR021 PR00H.BIT.srpr02
#define IICPR021 PR00H.BIT.srpr02
#define SRPR02 PR00H.BIT.srpr02
#define SREPR02 PR00H.BIT.tmpr011h
#define TMPR011H PR00H.BIT.tmpr011h
#define DMAPR00 PR00H.BIT.dmapr00
#define DMAPR01 PR00H.BIT.dmapr01
#define CSIPR000 PR00H.BIT.stpr00
#define IICPR000 PR00H.BIT.stpr00
#define STPR00 PR00H.BIT.stpr00
#define CSIPR001 PR00H.BIT.srpr00
#define IICPR001 PR00H.BIT.srpr00
#define SRPR00 PR00H.BIT.srpr00
#define SREPR00 PR00H.BIT.tmpr001h
#define TMPR001H PR00H.BIT.tmpr001h
#define CSIPR010 PR01.BIT.stpr01
#define IICPR010 PR01.BIT.stpr01
#define STPR01 PR01.BIT.stpr01
#define CSIPR011 PR01.BIT.srpr01
#define IICPR011 PR01.BIT.srpr01
#define SRPR01 PR01.BIT.srpr01
#define SREPR01 PR01.BIT.tmpr003h
#define TMPR003H PR01.BIT.tmpr003h
#define IICAPR00 PR01.BIT.iicapr00
#define TMPR000 PR01.BIT.tmpr000
#define TMPR001 PR01.BIT.tmpr001
#define TMPR002 PR01.BIT.tmpr002
#define TMPR003 PR01.BIT.tmpr003
#define ADPR0 PR01H.BIT.adpr0
#define RTCPR0 PR01H.BIT.rtcpr0
#define ITPR0 PR01H.BIT.itpr0
#define KRPR0 PR01H.BIT.krpr0
#define CSIPR030 PR01H.BIT.stpr03
#define IICPR030 PR01H.BIT.stpr03
#define STPR03 PR01H.BIT.stpr03
#define CSIPR031 PR01H.BIT.srpr03
#define IICPR031 PR01H.BIT.srpr03
#define SRPR03 PR01H.BIT.srpr03
#define TMPR013 PR01H.BIT.tmpr013
#define TMPR004 PR01H.BIT.tmpr004
#define WDTIPR1 PR10.BIT.wdtipr1
#define LVIPR1 PR10.BIT.lvipr1
#define PPR10 PR10.BIT.ppr10
#define PPR11 PR10.BIT.ppr11
#define PPR12 PR10.BIT.ppr12
#define PPR13 PR10.BIT.ppr13
#define PPR14 PR10.BIT.ppr14
#define PPR15 PR10.BIT.ppr15
#define CSIPR120 PR10H.BIT.stpr12
#define IICPR120 PR10H.BIT.stpr12
#define STPR12 PR10H.BIT.stpr12
#define CSIPR121 PR10H.BIT.srpr12
#define IICPR121 PR10H.BIT.srpr12
#define SRPR12 PR10H.BIT.srpr12
#define SREPR12 PR10H.BIT.tmpr111h
#define TMPR111H PR10H.BIT.tmpr111h
#define DMAPR10 PR10H.BIT.dmapr10
#define DMAPR11 PR10H.BIT.dmapr11
#define CSIPR100 PR10H.BIT.stpr10
#define IICPR100 PR10H.BIT.stpr10
#define STPR10 PR10H.BIT.stpr10
#define CSIPR101 PR10H.BIT.srpr10
#define IICPR101 PR10H.BIT.srpr10
#define SRPR10 PR10H.BIT.srpr10
#define SREPR10 PR10H.BIT.tmpr101h
#define TMPR101H PR10H.BIT.tmpr101h
#define CSIPR110 PR11.BIT.stpr11
#define IICPR110 PR11.BIT.stpr11
#define STPR11 PR11.BIT.stpr11
#define CSIPR111 PR11.BIT.srpr11
#define IICPR111 PR11.BIT.srpr11
#define SRPR11 PR11.BIT.srpr11
#define SREPR11 PR11.BIT.tmpr103h
#define TMPR103H PR11.BIT.tmpr103h
#define IICAPR10 PR11.BIT.iicapr10
#define TMPR100 PR11.BIT.tmpr100
#define TMPR101 PR11.BIT.tmpr101
#define TMPR102 PR11.BIT.tmpr102
#define TMPR103 PR11.BIT.tmpr103
#define ADPR1 PR11H.BIT.adpr1
#define RTCPR1 PR11H.BIT.rtcpr1
#define ITPR1 PR11H.BIT.itpr1
#define KRPR1 PR11H.BIT.krpr1
#define CSIPR130 PR11H.BIT.stpr13
#define IICPR130 PR11H.BIT.stpr13
#define STPR13 PR11H.BIT.stpr13
#define CSIPR131 PR11H.BIT.srpr13
#define IICPR131 PR11H.BIT.srpr13
#define SRPR13 PR11H.BIT.srpr13
#define TMPR113 PR11H.BIT.tmpr113
#define TMPR104 PR11H.BIT.tmpr104
#define MAA PMC.BIT.maa

/*
 Interrupt vector addresses
 */
#define RST_vect (0x0)
#define INTDBG_vect (0x2)
#define INTWDTI_vect (0x4)
#define INTLVI_vect (0x6)
#define INTP0_vect (0x8)
#define INTP1_vect (0xA)
#define INTP2_vect (0xC)
#define INTP3_vect (0xE)
#define INTP4_vect (0x10)
#define INTP5_vect (0x12)
#define INTCSI20_vect (0x14)
#define INTIIC20_vect (0x14)
#define INTST2_vect (0x14)
#define INTCSI21_vect (0x16)
#define INTIIC21_vect (0x16)
#define INTSR2_vect (0x16)
#define INTSRE2_vect (0x18)
#define INTTM11H_vect (0x18)
#define INTDMA0_vect (0x1A)
#define INTDMA1_vect (0x1C)
#define INTCSI00_vect (0x1E)
#define INTIIC00_vect (0x1E)
#define INTST0_vect (0x1E)
#define INTCSI01_vect (0x20)
#define INTIIC01_vect (0x20)
#define INTSR0_vect (0x20)
#define INTSRE0_vect (0x22)
#define INTTM01H_vect (0x22)
#define INTCSI10_vect (0x24)
#define INTIIC10_vect (0x24)
#define INTST1_vect (0x24)
#define INTCSI11_vect (0x26)
#define INTIIC11_vect (0x26)
#define INTSR1_vect (0x26)
#define INTSRE1_vect (0x28)
#define INTTM03H_vect (0x28)
#define INTIICA0_vect (0x2A)
#define INTTM00_vect (0x2C)
#define INTTM01_vect (0x2E)
#define INTTM02_vect (0x30)
#define INTTM03_vect (0x32)
#define INTAD_vect (0x34)
#define INTRTC_vect (0x36)
#define INTIT_vect (0x38)
#define INTKR_vect (0x3A)
#define INTCSI30_vect (0x3C)
#define INTIIC30_vect (0x3C)
#define INTST3_vect (0x3C)
#define INTCSI31_vect (0x3E)
#define INTIIC31_vect (0x3E)
#define INTSR3_vect (0x3E)
#define INTTM13_vect (0x40)
#define INTTM04_vect (0x42)
#define INTTM05_vect (0x44)
#define INTTM06_vect (0x46)
#define INTTM07_vect (0x48)
#define INTP6_vect (0x4A)
#define INTP7_vect (0x4C)
#define INTP8_vect (0x4E)
#define INTP9_vect (0x50)
#define INTP10_vect (0x52)
#define INTP11_vect (0x54)
#define INTTM10_vect (0x56)
#define INTTM11_vect (0x58)
#define INTTM12_vect (0x5A)
#define INTSRE3_vect (0x5C)
#define INTTM13H_vect (0x5C)
#define INTMD_vect (0x5E)
#define INTIICA1_vect (0x60)
#define INTFL_vect (0x62)
#define INTDMA2_vect (0x64)
#define INTDMA3_vect (0x66)
#define INTTM14_vect (0x68)
#define INTTM15_vect (0x6A)
#define INTTM16_vect (0x6C)
#define INTTM17_vect (0x6E)
#define BRK_I_vect (0x7E)
#define OPTION_BYTES_vect (0xC0)
#define SECURITY_ID_vect (0xC4)
#endif
